### ISSUE TITLE
Estaría mejor si usamos carpetas de css y assets

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/d-s1-evaluacion-intermedia-Fanyfa#1]
La estructura que os proponemos la puedes ver en https://books.adalab.es/materiales-front-end-d/sprint-1.-hola-mundo/1.1.-intro-a-la-web#notas-finales-sobre-como-organizar-nuestro-proyecto

**Comment by Fanyfa** [comment]
Hecho!
